inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - lib/templates/rails/scaffold_controller/controller.rb
    - db/schema.rb
    - vendor/**/*
    - lib/capistrano/**/*
    - spec/fixtures/language_support_submissions/program.rb

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false
