#!/bin/sh
if [ ! -f program.c ]; then
    echo "Program file 'program.c' not found. Did you add this to the root of your ZIP file (no subdirectories)?"
    exit 1
fi

gcc program.c -o program -lm && ./program

if [ $? -ne 0 ]; then
  echo
  echo "WARNING: there were problems with your submission."
  echo "Some tips below"
  echo
  echo "No file 'run' supplied. Assuming defaults"
  echo "Running: 'gcc program.c -o program -lm && ./program'"
fi
