#!/bin/sh
if [ ! -f program.cpp ]; then
    echo "Program file 'program.cpp' not found. Did you add this to the root of your ZIP file (no subdirectories)?"
    exit 1
fi

g++ program.cpp -o program && ./program


if [ $? -ne 0 ]; then
  echo
  echo "WARNING: there were problems with your submission."
  echo "Some tips below"
  echo
  echo "No file 'run' supplied. Assuming defaults"
  echo "Running: 'g++ program.cpp -o program -lm && ./program'"
fi
