#!/bin/sh
if [ ! -f program.js ]; then
    echo "Program file 'program.js' not found. Did you add this to the root of your ZIP file (no subdirectories)?"
    exit 1
fi

echo "No file 'run' supplied. Assuming defaults"
echo "Running: 'node program.js'"
node program.js
