#!/bin/sh
if [ ! -f program.lisp ]; then
    echo "Program file 'program.lisp' not found. Did you add this to the root of your ZIP file (no subdirectories)?"
    exit 1
fi

clisp program.lisp

if [ $? -ne 0 ]; then
  echo
  echo "WARNING: there were problems with your submission."
  echo "Some tips below"
  echo
  echo "No file 'run' supplied. Assuming defaults"
  echo "Running: 'clisp program.lisp'"
fi
