#!/bin/sh
if [ ! -f program.py ]; then
    echo "Program file 'program.py' not found. Did you add this to the root of your ZIP file (no subdirectories)?"
    exit 1
fi

python3 program.py

if [ $? -ne 0 ]; then
  echo
  echo "WARNING: there were problems with your submission."
  echo "Some tips below"
  echo
  echo "No file 'run' supplied. Assuming defaults"
  echo "Running: 'python3 program.py'"
fi
