#!/bin/sh
if [ ! -f program.rb ]; then
    echo "Program file 'program.rb' not found. Did you add this to the root of your ZIP file (no subdirectories)?"
    exit 1
fi
echo "No file 'run' supplied. Assuming defaults"
echo "Running: 'ruby program.rb'"
ruby program.rb
